[package]
name = "monitor"
version.workspace = true
edition.workspace = true

[dependencies]
debug-core = { path = "../debug-core" }
elf-info = { path = "../elf-info" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
parking_lot.workspace = true
crossbeam-channel.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_Media"] }
