[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "1.2.31"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tracing = "0.1"
parking_lot = "0.12"
crossbeam-channel = "0.5"

[profile.dev]
# 调试内核依赖（probe-rs/gimli）在 O0 下过慢，统一给依赖开优化
opt-level = 1

[profile.dev.package."*"]
opt-level = 2

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
